
const SET_PROGRESS = 'SET_PROGRESS'

const PROMISE_PENDING = 'PROMISE_PENDING'
const PROMISE_SUCCESS = 'PROMISE_SUCCESS'
const PROMISE_FAILURE = 'PROMISE_FAILURE'

const ADD_TOAST = 'ADD_TOAST'
const DELETE_TOAST = 'DELETE_TOAST'

const SET_ENV = 'SET_ENV'
const ENV_KEY = 'ENV_KEY'

const SET_ENV_I18N = 'SET_ENV_I18N'

const SET_AUTH = 'SET_AUTH'
const AUTH_KEY = 'XSD_AUTH_KEY'
const SET_USER = 'SET_USER'
const SET_PROFILE = 'SET_PROFILE'

const CART_KEY = 'XSD_CART_KEY'
const SET_CART = 'SET_CART'

const NAVIGATOR_KEY = 'NAVIGATOR_KEY'
const SET_NAV_MAIN_ROUTES = 'SET_NAV_MAIN_ROUTES'
const SET_NAV_CURR_ROUTE = 'SET_NAV_CURR_ROUTE'

const SET_ITEMS = 'SET_ITEMS'
const ADD_ITEM = 'ADD_ITEM'
const UPDATE_ITEM = 'UPDATE_ITEM'
const REMOVE_ITEM = 'REMOVE_ITEM'
const SET_ACTIVITY_ITEM = 'SET_ACTIVITY_ITEM'

const SET_FAVORITES = 'SET_FAVORITES'

const SET_NOTICES = 'SET_NOTICES'
const ADD_NOTICE = 'ADD_NOTICE'
const REMOVE_NOTICE = 'REMOVE_NOTICE'
const UPDATE_NOTICE = 'UPDATE_NOTICE'

const SET_TRANSES = 'SET_TRANSES'
const SET_WORKS = 'SET_WORKS'

export default { 
    PROMISE_PENDING, 
    PROMISE_SUCCESS, 
    PROMISE_FAILURE, 

    SET_PROGRESS, 
    ADD_TOAST, 
    DELETE_TOAST,
    SET_ENV,
    ENV_KEY,
    SET_ENV_I18N,

    SET_AUTH,
    AUTH_KEY,
    SET_USER,
    SET_PROFILE,

    CART_KEY,
    SET_CART,

    NAVIGATOR_KEY,
    SET_NAV_MAIN_ROUTES,
    SET_NAV_CURR_ROUTE,
    
    SET_ITEMS,
    ADD_ITEM,
    UPDATE_ITEM,
    REMOVE_ITEM,
    SET_ACTIVITY_ITEM,

    SET_FAVORITES,

    SET_NOTICES,
    ADD_NOTICE,
    REMOVE_NOTICE,
    UPDATE_NOTICE,

    SET_TRANSES,
    SET_WORKS,

}

